<Project>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.15.0" PrivateAssets="all" />
    <PackageReference Include="KubernetesClient" Version="17.0.14" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.73.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.73.1" PrivateAssets="all" />
  </ItemGroup>
</Project>
